steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  # Run tests
  - name: 'gcr.io/cloud-builders/npm'
    args: ['test', '--', '--no-watch', '--no-progress', '--browsers=ChromeHeadlessCI']
    env:
      - 'CHROME_BIN=/usr/bin/chromium-browser'
  # Build the application for production
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build:prod']
  # Archive the build artifacts (optional, but good practice for deployment)
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['artifacts', 'upload', '--repository=your-repo-name', '--location=your-location', '--source=dist/sazon-del-bueno-frontend']
